### ISSUE TITLE
Incorrect render of example scene

### ISSUE THREAD

**Issue by Darylgolden** [ManimCommunity/manim-renderer#10]
https://user-images.githubusercontent.com/9102529/104978725-7e18ee00-5a3d-11eb-852b-cb757a0e81a2.mp4

(Expected render is located at https://docs.manim.community/en/latest/examples.html#pointwithtrace )

Using the windows renderer.

**Comment by eulertour** [comment]
I'm actually sort of surprised it even worked that well with updaters. Luckily I don't think the solution is too complicated, I'll just have to update scenes containing updaters frame by frame rather than skip all the way to the end.

**Comment by eulertour** [comment]
This will be fixed after ManimCommunity/manim#952 and the tweening branch are merged.

**Comment by eulertour** [comment]
Fixed with ManimCommunity/manim#952 and #11.
